fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
  symlinks:
    consul: "#{source_dir}"
