---
language: ruby
bundler_args: --without development --full-index
before_install: rm Gemfile.lock || true
sudo: false
cache: bundler
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.4.3
    env: PUPPET_VERSION="~> 5.0"
  - rvm: 2.5.0
    env: PUPPET_VERSION="~> 5.0"
