---
language: ruby
bundler_args: --without development --full-index
before_install: rm Gemfile.lock || true
sudo: false
cache: bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.8.4"
  - PUPPET_VERSION="~> 3.8.4" FUTURE_PARSER=yes STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0"
matrix:
  exclude:
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.4.0"
  - rvm: 1.9
    env: PUPPET_VERSION="~> 4.1.0"
  - rvm: 2.0
    env: PUPPET_VERSION="~> 4.1.0"
